resources:
  - url: http://127.0.0.1:5000/charger-card.js
    type: module
views:
  - cards:
      - type: custom:charger-card
        name: Charger Card Development
        entity: sun.sun
        test_gui: true
